[package]
name = "svm-rs"
version = "0.2.22"
edition = "2018"
authors = ["Rohit Narurkar <rohit.narurkar@protonmail.com>"]
license = "MIT OR Apache-2.0"
description = """
Solidity-Compiler (Solc) Version Manager.
"""
readme = "README.md"
repository = "https://github.com/roynalnaruto/svm-rs"
homepage = "https://github.com/roynalnaruto/svm-rs"

[lib]
name = "svm_lib"
path = "src/lib.rs"

[[bin]]
name = "solc"
path = "src/solc/main.rs"

[[bin]]
name = "svm"
path = "src/svm/main.rs"

[dependencies]
anyhow = { version = "1.0.70", default-features = false, features = ["std"] }
cfg-if = { version = "1.0.0", default-features = false }
clap = { version = "4.2.0", features = ["derive"] }
console = { version = "0.15.5", default-features = false }
dialoguer = { version = "0.10.3", default-features = false }
fs2 = "0.4.3"
hex = { version = "0.4.3", default-features = false, features = ["std"] }
home = { version = "0.5.4", default-features = false }
indicatif = { version = "0.17.3", default-features = false }
itertools = { version = "0.10.5", default-features = false, features = ["use_std"] }
once_cell = { version = "1.17.1", default-features = false }
rand = { version = "0.8.5", default-features = false, features = ["std", "std_rng"] }
reqwest = { version = "0.11.16", default-features = false, features = ["json"] }
semver = { version = "1.0.17", default-features = false, features = ["std", "serde"] }
serde = { version = "1.0.159", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.95", default-features = false }
sha2 = { version = "0.10.6", default-features = false }
tempfile = { version = "3.5.0", default-features = false }
thiserror = { version = "1.0.40", default-features = false }
tokio = { version = "1.27.0", features = ["full"] }
tracing = "0.1.37"
url = { version = "2.3.1", default-features = false }

[target.'cfg(all(target_os = "windows", target_arch = "x86_64"))'.dependencies]
zip = "0.6.4"

[build-dependencies]
home = { version = "0.5.4", default-features = false }

[features]
default = ["rustls"]
openssl = ["reqwest/native-tls"]
rustls = ["reqwest/rustls-tls"]
sha2-asm = ["sha2/asm"]
blocking = ["reqwest/blocking"]

[workspace]
members = ["svm-builds"]
